AWSTemplateFormatVersion: '2010-09-09'
Description: Doctor Service REST APIs (Lambda + API Gateway + CloudWatch + S3 JSON DB)

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]

  ServiceName:
    Type: String

  CodeBucket:
    Type: String

  CodeKey:
    Type: String

  DatabaseBucket:
    Type: String

  DatabaseKey:
    Type: String

Resources:

# =========================================================
# IAM ROLE
# =========================================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-${ServiceName}-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: lambda-s3-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${CodeBucket}
                  - !Sub arn:aws:s3:::${CodeBucket}/*
                  # Database bucket (FIX)
                  - !Sub arn:aws:s3:::${DatabaseBucket}
                  - !Sub arn:aws:s3:::${DatabaseBucket}/*

# =========================================================
# LAMBDA FUNCTION (ZIP FROM S3)
# =========================================================
  DoctorServiceFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub "${Environment}-jsvm-${ServiceName}-lambda"
      Runtime: python3.11
      Handler: lambda_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 20

      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey

      Environment:
        Variables:
          DATABASE_BUCKET: !Ref DatabaseBucket
          DATABASE_KEY: !Ref DatabaseKey

# =========================================================
# API GATEWAY
# =========================================================
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${Environment}-${ServiceName}-api"

  Items:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref Api
      ParentId: !GetAtt Api.RootResourceId
      PathPart: items

  Item:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref Api
      ParentId: !GetAtt Api.RootResourceId
      PathPart: item

# =========================================================
# METHODS
# =========================================================
  GetItems:
    Type: AWS::ApiGateway::Method
#    DependsOn: LambdaPermission
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref Items
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DoctorServiceFunction.Arn}/invocations
  CreateItem:
    Type: AWS::ApiGateway::Method
#    DependsOn: LambdaPermission
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref Item
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DoctorServiceFunction.Arn}/invocations


# =========================================================
# CLOUDWATCH LOG GROUP
# =========================================================
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Environment}-${ServiceName}"
      RetentionInDays: 14


# =========================================================
# PERMISSION
# =========================================================
  LambdaPermission:
    Type: AWS::Lambda::Permission
#    DependsOn: DoctorServiceFunction
    Properties:
      FunctionName: !Ref DoctorServiceFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/*

# =========================================================
# DEPLOYMENT + STAGE
# =========================================================
  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetItems
      - CreateItem
    Properties:
      RestApiId: !Ref Api
      StageName: !Ref Environment

# =========================================================
# OUTPUT
# =========================================================
Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"