name: Doctor service CI/CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # 4. Create output folder
      - name: Prepare build folders
        run: |
          rm -rf output build layer
          mkdir -p output
          mkdir -p layer/python

      # 5. Build Lambda Layer (common code)
      - name: Build Lambda Layer
        run: |
          cd layer
          zip -r ../output/common-layer.zip python

      # 6. Build Lambda functions
      - name: Build Lambda zips
        run: |
          for fn in lambdas/*; do
            FUNCTION=$(basename "$fn")
            echo "Building $FUNCTION"

            BUILD_DIR="build/$FUNCTION"
            ZIP_FILE="output/$FUNCTION.zip"

            mkdir -p "$BUILD_DIR"

            cp -r "lambdas/$FUNCTION/"* "$BUILD_DIR/"

            if [ -f "lambdas/$FUNCTION/requirements.txt" ]; then
              pip install -r "lambdas/$FUNCTION/requirements.txt" -t "$BUILD_DIR/"
            fi

            cd "$BUILD_DIR"
            zip -r "../../$ZIP_FILE" . -x "*.pyc" "__pycache__/*"
            cd -
            rm -rf "$BUILD_DIR"
          done

      # 7. Upload artifacts to S3
      - name: Upload to S3
        run: |
          for file in output/*.zip; do
            echo "Uploading $file"
            aws s3 cp "$file" s3://s3-jsvm-dev-env/
          done

      # 8. Deploy CloudFormation stack
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cft-ak-doctor-service.yaml \
            --stack-name  doctor-crud-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-2
